/**
 * Register listeners
 */
import browserMethods from '@/browserMethods';
import onBeforeNavigate from '@/background/listeners/onBeforeNavigate';
import onCompletedNavigate from '@/background/listeners/onCompletedNavigate';
import onTabActivated from '@/background/listeners/onTabActivated';
import onTabHistoryRequest from '@/background/listeners/onTabHistoryRequest';
import onTabRemoved from '@/background/listeners/onTabRemoved';
import onUpdateInstitutions from '@/background/listeners/onUpdateInstitutions';
import onContextMenuClick from '@/background/listeners/onContextMenuClick';
import onToolbarClicked from '@/background/listeners/onToolbarClicked';
import triggerStateMachineFeatures from '@/background/listeners/triggerStateMachineFeatures';
import onToggleAppActive from '@/background/listeners/onToggleAppActive';
import onInstalled from '@/background/listeners/onInstalled';
import onAlarm from '@/background/listeners/onAlarm';
import onUpdateUserPreferences from '@/background/listeners/onUpdateUserPreferences';
import onFetchBaseData from '@/background/listeners/onFetchBaseData';
import onAddClosedPopupToHistory from '@/background/listeners/onAddClosedPopupToHistory';
import onLibrarySearchQuery from '@/background/listeners/onLibrarySearchQuery';
import onHttpRequest from '@/background/listeners/onHttpRequest';
import onUpdateAvailable from '@/background/listeners/onUpdateAvailable';
import onStartup from '@/background/listeners/onStartup';
import onNetworkChange from '@/background/listeners/onNetworkChange';
import onStatEventAccess from '@/background/listeners/onStatEventAccess';
import onStatEventFutures from '@/background/listeners/onStatEventFutures';
import onSignedInDomainsRequest from '@/background/listeners/onSignedInDomainsRequest';
import onCommittedNavigate from '@/background/listeners/onCommittedNavigate';
import onGetFormattedCitation from '@/background/listeners/onGetFormattedCitation';
import onFetchAnnotations from '@/background/listeners/onFetchAnnotations';
import onSaveHighlightedText from '@/background/listeners/onSaveHighlightedText';
import onUpdateAnnotation from '@/background/listeners/onUpdateAnnotation';
import onDeleteAnnotation from '@/background/listeners/onDeleteAnnotation';
import onAddSignedInDomains from '@/background/listeners/onAddSignedInDomains';
import onFetchUser from '@/background/listeners/onFetchUser';
import onSignOut from '@/background/listeners/onSignOut';
import onWindowCreated from '@/background/listeners/onWindowCreated';
import onOpenNewTab from '@/background/listeners/onOpenNewTab';

browserMethods.alarms.background.listeners.onAlarm(onAlarm);
browserMethods.app.background.listeners.onAddClosedPopupToHistory(onAddClosedPopupToHistory);
browserMethods.app.background.listeners.onInstalled(onInstalled);
browserMethods.app.background.listeners.onDetermineAvailableFeatures(triggerStateMachineFeatures);
browserMethods.app.background.listeners.onFetchBaseData(onFetchBaseData);
browserMethods.app.background.listeners.onFetchUser(onFetchUser);
browserMethods.app.background.listeners.onSignOut(onSignOut);
browserMethods.app.background.listeners.onToggleAppActive(onToggleAppActive);
browserMethods.app.background.listeners.onUpdateInstitutions(onUpdateInstitutions);
browserMethods.app.background.listeners.onUpdateUserPreferences(onUpdateUserPreferences);
browserMethods.app.background.listeners.onLibrarySearchQuery(onLibrarySearchQuery);
browserMethods.app.background.listeners.onGetFormattedCitation(onGetFormattedCitation);
browserMethods.app.background.listeners.onFetchAnnotations(onFetchAnnotations);
browserMethods.app.background.listeners.onSaveHighlightedText(onSaveHighlightedText);
browserMethods.app.background.listeners.onUpdateAnnotation(onUpdateAnnotation);
browserMethods.app.background.listeners.onDeleteAnnotation(onDeleteAnnotation);
browserMethods.app.background.listeners.onHttpRequest(onHttpRequest);
browserMethods.app.background.listeners.onStatEventAccess(onStatEventAccess);
browserMethods.app.background.listeners.onStatEventFutures(onStatEventFutures);
browserMethods.app.background.listeners.onSignedInDomainsRequest(onSignedInDomainsRequest);
browserMethods.app.background.listeners.onAddSignedInDomains(onAddSignedInDomains);
browserMethods.app.background.listeners.onOpenNewTab(onOpenNewTab);
browserMethods.contextMenus.background.listeners.onClick(onContextMenuClick);
browserMethods.navigation.onBeforeNavigate(onBeforeNavigate);
browserMethods.navigation.onCommitted(onCommittedNavigate);
browserMethods.navigation.onCompleted(onCompletedNavigate);
browserMethods.network.background.listeners.onChanged(onNetworkChange);
browserMethods.runtime.onUpdateAvailable(onUpdateAvailable);
browserMethods.tabs.background.listeners.onActivated(onTabActivated);
browserMethods.tabs.background.listeners.onRemoved(onTabRemoved);
browserMethods.tabs.background.listeners.onTabCreate();
browserMethods.tabs.background.listeners.onTabHistoryRequest(onTabHistoryRequest);
browserMethods.toolbar.background.listeners.onClicked(onToolbarClicked);
browserMethods.runtime.onStartup(onStartup);
browserMethods.windows.background.listeners.onCreated(onWindowCreated);
