// Type of Lla Stat, originally names of redux actions
enum LLAStatType {
  OPEN_ONBOARDING_TUTORIAL = 'SETTINGS/OPEN_ONBOARDING_TUTORIAL',
  UPDATE_SETTINGS = 'SETTINGS/UPDATE_SETTINGS',
  AUTO_REDIRECT = 'SESSION/AUTO_REDIRECT',
  CONTENT_POPUP_RENDERED = 'SESSION/CONTENT_POPUP_RENDERED',
  TOOLBAR_POPUP_RENDERED = 'SESSION/TOOLBAR_POPUP_RENDERED',
  CUSTOM_REDIRECT = 'SESSION/CUSTOM_REDIRECT',
  ENHANCE_SEARCH = 'SESSION/ENHANCE_SEARCH',
  PROCESS_CLICK = 'SESSION/PROCESS_CLICK',
  SET_TAB_STATE = 'SESSION/SET_TAB_STATE',
  SEARCH_ENGINE_SEARCH = 'SEARCH_ENGINES/SEARCH',
  ADD_BADGES = 'SCITE/ADD_BADGES',
  CLICK_BADGE = 'SCITE/CLICK_BADGE',
  CONNECT = 'SESSION/CONNECT',
}

export default LLAStatType;
