/**
 * librarySearchTestData
 */
/* cSpell:disable */
/* eslint-disable */
export const libraryProvidersTestData = {
  library_searches: [
    {
      uuid: '9f95c40a-4838-4fc0-b446-7e2d26e59ca8',
      name: 'Sharepoint',
      sourceType: 'sharepoint',
      sourceUrl: 'https://getworkflow.sharepoint.com/',
      shownOnGoogle: true,
      shownOnGoogleScholar: true,
      viewMore: null,
      documentLink: null,
      apiKey: null,
      responseType: null,
      filesExcluded: null,
      institutionId: null,
      wskey: null,
      secret: null,
      custId: null,
      profileId: null,
      groupId: null,
      authType: null,
      apiUserId: null,
      apiPassword: null,
    },
    {
      uuid: 'beeedb61-d265-4764-a76a-452a945dc101',
      name: 'Custom',
      sourceType: 'custom',
      sourceUrl: 'https://gmd.rs/test/j.php',
      shownOnGoogle: true,
      shownOnGoogleScholar: true,
      viewMore: null,
      documentLink: null,
      apiKey: null,
      responseType: 'json',
      filesExcluded: null,
      institutionId: null,
      wskey: null,
      secret: null,
      custId: null,
      profileId: null,
      groupId: null,
      authType: null,
      apiUserId: null,
      apiPassword: null,
    },
    {
      uuid: '5b571b07-e604-48e2-aec9-6f6d88ac3487',
      name: 'Ebsco',
      sourceType: 'ebsco',
      sourceUrl: 'https://eds-api.ebscohost.com',
      shownOnGoogle: true,
      shownOnGoogleScholar: true,
      viewMore: null,
      documentLink: null,
      apiKey: null,
      responseType: null,
      filesExcluded: null,
      institutionId: null,
      wskey: null,
      secret: null,
      custId: 'bellvue',
      profileId: 'edsapi',
      groupId: 'main',
      authType: null,
      apiUserId: 'PoQHQEnIbb1MBYr)Ir2E',
      apiPassword: 'f8)lLJ0gTk4g^8(QO$Gf',
    },
    {
      uuid: 'bee98421-e1e4-4df3-8ec9-8216aafb504d',
      name: 'UAB',
      sourceType: 'exlibris',
      sourceUrl: 'https://api-eu.hosted.exlibrisgroup.com/primo/v1/search/?vid=34CSUC_UAB:VU1&tab=Everything&scope=MyInst_and_CI&q=any,contains,[search_query]&apikey=l8xx9cacfeea616a4f6294340c28c5425629',
      shownOnGoogle: true,
      shownOnGoogleScholar: true,
      viewMore: 'https://bibcercador.uab.cat/discovery/search?query=any,contains,[search_query]&tab=Everything&search_scope=MyInst_and_CI&vid=34CSUC_UAB:VU1',
      documentLink: 'https://bibcercador.uab.cat/discovery/fulldisplay?docid=[document_id]&vid=34CSUC_UAB:VU1&search_scope=MyInst_and_CI&tab=Everything&query=any,contains,[search_query]',
      apiKey: 'l8xx9cacfeea616a4f6294340c28c5425629',
      responseType: null,
      filesExcluded: null,
      institutionId: null,
      wskey: null,
      secret: null,
      custId: null,
      profileId: null,
      groupId: null,
      authType: null,
      apiUserId: null,
      apiPassword: null,
    },
    {
      uuid: '9b0624b4-84d4-41f7-82ea-19b984d0c7cf',
      name: 'JSTOR',
      sourceType: 'jstor',
      sourceUrl: 'https://www.jstor.org/action/doXmlSearch?query=dc.title+%3D+%22[search_query]%22&maximumRecords=15&startRecord=1&recordSchema=info%3Asrw%2Fschema%2F1%2Fdc-v1.1&operation=searchRetrieve&version=1.1&recordPacking=xml&includeXsl=false&source=test',
      shownOnGoogle: true,
      shownOnGoogleScholar: true,
      viewMore: null,
      documentLink: null,
      apiKey: null,
      responseType: null,
      filesExcluded: null,
      institutionId: null,
      wskey: null,
      secret: null,
      custId: null,
      profileId: null,
      groupId: null,
      authType: null,
      apiUserId: null,
      apiPassword: null,
    },
    {
      uuid: 'b2884a2e-ba78-4d80-a5cc-7a06ad37dc0f',
      name: 'JSTOR',
      sourceType: 'jstor',
      sourceUrl: 'https://discovery.api.oclc.org/worldcat-org-ci/search/summary-bibs?q=[search_query]&heldByInstitutionID=128807&limit=15',
      shownOnGoogle: true,
      shownOnGoogleScholar: false,
      viewMore: null,
      documentLink: null,
      apiKey: null,
      responseType: null,
      filesExcluded: null,
      institutionId: null,
      wskey: null,
      secret: null,
      custId: null,
      profileId: null,
      groupId: null,
      authType: null,
      apiUserId: null,
      apiPassword: null,
    },
  ],
  source_types: [
    {
      name: 'Jstor',
      order: 1,
    },
    {
      name: 'Jove',
      order: 2,
    },
    {
      name: 'Ebsco',
      order: 3,
    },
    {
      name: 'Sharepoint',
      order: 4,
    },
    {
      name: 'Confluence',
      order: 5,
    },
    {
      name: 'Exlibris',
      order: 6,
    },
    {
      name: 'Tdnet',
      order: 7,
    },
    {
      name: 'Trip',
      order: 8,
    },
    {
      name: 'Worldcat',
      order: 9,
    },
    {
      name: 'Custom',
      order: 10,
    },
  ],
};


export const libraryResultsTestData = [
  {
    id: '1',
    title: 'The concepts of stress and stress system disorders: overview of physical and behavioral homeostasis',
    authors: 'GP Chrousos, PW Gold - Jama, 1992 - jamanetwork.com',
    text: 'Objective.  —This article defines stress and related concepts and reviews their historical development. The notion of a stress system as the effector of the stress',
    href: 'https://www.leanlibrary.com',
  },
  {
    id: '2',
    title: 'Some other piece of content',
    authors: 'GP Chrousos, PW Gold - Jama, 1992 - jamanetwork.com',
    text: 'Lorem Ipsum dolor Objective. — This article defines stress and related concepts and reviews their historical development. The notion of a stress system as the effector of the stress',
    href: 'https://www.example.com',
  },
];

/* eslint-enable */
/* cSpell:enable */
