interface UsersSavedArticles {
  id: string,
  newId: string | null,
  tags: string[],
  authors: string[],
  firstAuthorsForView: string[],
  lastAuthorForView: string | null,
  title: string,
  plainTitle: string,
  rating: number,
  publicationInfo: string,
  factor: number,
  articleId: string,
  pubMedId: string | null,
  doi: string,
  pmcId: string | null,
  type: string,
  publishedDate: number,
  publishedDay: number | null,
  publishedMonth: number,
  publishedYear: number,
  originalPublishedYear: number | null,
  itemType: string,
  itemTypeValue: string,
  itemSubType: string | null,
  notes: string | null,
  numberOfAnnotations: number,
  pdfResource: string | null,
  fullTextLink: string,
  status: string,
  accessedDate: number | null,
  edition: string | null,
  issue: string,
  journalName: string,
  journalAbbreviation: string,
  journalTitle: string,
  websiteTitle: string | null,
  pagination: string,
  publicationPlace: string | null,
  publisher: string | null,
  softwareType: string,
  thesisType: string,
  url: string | null,
  version: string | null,
  volume: string,
  chapter: string | null,
  editors: string[],
  affiliations: string[],
  addedBy: {
    firstName: string,
    lastName: string,
    email: string,
    userId: string,
    me: boolean,
    initials: string,
    deleted: boolean,
  },
  addedDate: number,
  referrer: string | null,
  numberOfVolumes: number | null,
  isbn: string | null,
  abstractText: string | null,
  sfxQueryString: string,
  bookExtraInfo: string | null,
  inReadingList: boolean,
  candidateForProxy: boolean,
  affiliationText: string | null,
  subType: string | null,
  onlineReference: boolean,
  translators: string[],
  patentExtraInfo: string | null,
  conferenceExtraInfo: string | null,
  proceedingsTitle: string | null,
  conferenceName: string | null,
  pageTitle: string | null,
}

export default UsersSavedArticles;
