import State from '@/enums/State';

export default [
  State.RedirectLoop,
  State.SystemMessage,
  State.CustomRedirected,
  State.FullTextFinder,
  State.OpenAccess,
  State.EbookFinder,
  State.EbookFinderMultiple,
  State.OpenAccessEbook,
  State.ProxyAccessPossible,
  State.OpenAthensAccessPossible,
  State.ShibbolethAccessPossible,
  // not sure if this is the right place
  State.PrintBookAvailable,
  State.OrderForm,
  State.FullTextFinderAchieved,
  State.OpenAccessAchieved,
  State.EbookFinderAchieved,
  State.PriorityAssist,
  State.Assist,
  State.Modal,
  State.Campaign,
  State.GoogleScholarSearchEnhanced,
  State.PubMedSearchEnhanced,
  State.OnCampusSupported,
  State.OnCampusNotSupported,
  State.AutoRedirected,
  State.ProxyAccessAchieved,
  State.OpenAthensAccessAchieved,
  State.ShibbolethAccessAchieved,
  State.OnboardingTutorial,
  State.NotSupported,
];
